Vagrant.configure("2") do |config|
    config.vm.define "zulvg"
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 4
    end
    config.vm.boot_timeout = 600 # Wait 10 mins for the VM to boot
    config.vm.network "forwarded_port", guest: 9000, host: 9000
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "forwarded_port", guest: 18000, host: 18000
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 9273, host: 9273
    config.vm.network "forwarded_port", guest: 9090, host: 9090

    # Use the file provisioner to copy a file from the host to the VM
    config.vm.provision "file" do |file|
      file.source = "../k8s/oidc-kube-config.yml"  # Path to the file in your host directory
      file.destination = "/home/vagrant/k8s/oidc-kube-config.yml"  # Path in the VM where the file should be copied
    end
    config.vm.provision "shell", path: "provision.sh"
end
  